/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zcr_com_ndk_JniTest */

#ifndef _Included_zcr_com_ndk_JniTest
#define _Included_zcr_com_ndk_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zcr_com_ndk_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zcr_com_ndk_JniTest_getString
  (JNIEnv *, jclass);

/*
 * Class:     zcr_com_ndk_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zcr_com_ndk_JniTest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     zcr_com_ndk_JniTest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zcr_com_ndk_JniTest_accessField
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
