/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zcr_com_ndk_VideoUtils */

#ifndef _Included_zcr_com_ndk_VideoUtils
#define _Included_zcr_com_ndk_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zcr_com_ndk_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zcr_com_ndk_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
