/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zcr_com_ndk_JniCTest */

#ifndef _Included_zcr_com_ndk_JniCTest
#define _Included_zcr_com_ndk_JniCTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zcr_com_ndk_JniCTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zcr_com_ndk_JniCTest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     zcr_com_ndk_JniCTest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zcr_com_ndk_JniCTest_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
